---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
getwd()
load("./adnimerge.rdata")
```


```{r}
ds <- list.dirs(path="C:/Users", recursive=FALSE)
bide <- paste(ds[5], "/Desktop/CONTROL_GROUP_ADNI3/CONTROL_GROUP_METADATA", sep="")
CN_ids <- list.dirs(bide, full.names=FALSE, recursive=FALSE)

bide <- paste(ds[5],"/Desktop/AD_GROUP_ADNI3/AD_GROUP_METADATA", sep="")
AD_ids <- list.dirs(bide, full.names=FALSE, recursive=FALSE)
```


```{r}
CN_data <- adnimerge[adnimerge$PTID %in% CN_ids, ]
# How many CN (70)
print(length(unique(CN_data$PTID)))

AD_data <- adnimerge[adnimerge$PTID %in% AD_ids, ]
# How many AD (?)
print(length(unique(AD_data$PTID)))
```

Get last visit from each subject
```{r}
AD_ids <- unique(AD_data$PTID)
CN_ids <- unique(CN_data$PTID)

filtered_AD <- data.frame()
for (i in 1:length(AD_ids))
  {
  tmp <- AD_data[AD_data$PTID == AD_ids[i], ]
  tmp <- tmp[nrow(tmp), ]
  filtered_AD[i, 1:ncol(tmp)] <- tmp
}

filtered_CN <- data.frame()
for (i in 1:length(CN_ids))
  {
  tmp <- CN_data[CN_data$PTID == CN_ids[i], ]
  tmp <- tmp[nrow(tmp), ]
  filtered_CN[i, 1:ncol(tmp)] <- tmp
}

# Select only the rows that we want
sel <- c("PTID", "DX.bl", "AGE", "PTGENDER", "PTEDUCAT", "APOE4", "ADAS11", "ADAS13", "MMSE", "ADAS11.bl", "ADAS13.bl", "MMSE.bl")

filt_AD <- filtered_AD[, sel]
filt_CN <- filtered_CN[, sel]
```

T-TEST OF DIFFERENCES FOR AGE
```{r}
vt <- var.test(filt_AD$AGE, filt_CN$AGE, alternative="two.sided")

varbool <- FALSE
if(vt$p.value > 0.05){
  varbool <- TRUE
}

AGEtest <- t.test(filt_AD$AGE, filt_CN$AGE, alternative="two.sided", var.equal=varbool)
AGEtest
```

CHI-SQUARE TEST FOR GENDERS
```{r}
library(gplots)
gendmat <- data.frame()
gendmat[1,1] <- sum(filt_CN$PTGENDER == "Female")
gendmat[2,1] <- sum(filt_CN$PTGENDER == "Male")
gendmat[1,2] <- sum(filt_AD$PTGENDER == "Female")
gendmat[2,2] <- sum(filt_AD$PTGENDER == "Male")
gendmat <- data.frame(gendmat, row.names=c("F", "M"))
colnames(gendmat) <- c("CN", "AD")

gender_chisq <- chisq.test(gendmat)
gender_chisq
```

T-TEST OF MMSE DIFFERENCES
```{r}
# Missing values, impute from MMSE.bl
idxs <- is.na(filt_AD$MMSE)
filt_AD$MMSE[idxs] <- filt_AD$MMSE.bl[idxs]
if (sum(is.na(filt_AD$MMSE)) != 0) # If NA remaining -> Impute with mean
{
  filt_AD$MMSE[is.na(filt_AD$MMSE)] = mean(filt_AD$MMSE, na.rm=TRUE)
}


idxs <- is.na(filt_CN$MMSE)
filt_CN$MMSE[idxs] <- filt_CN$MMSE.bl[idxs]
if (sum(is.na(filt_CN$MMSE)) != 0)
{
  filt_CN$MMSE[is.na(filt_CN$MMSE)] = mean(filt_CN$MMSE, na.rm=TRUE)
}


vt <- var.test(filt_AD$MMSE, filt_CN$MMSE, alternative="two.sided")

varbool <- FALSE
if(vt$p.value >= 0.05){
  varbool <- TRUE
}

MMSEtest <- t.test(filt_AD$MMSE, filt_CN$MMSE, alternative="two.sided", var.equal=varbool)
MMSEtest
```

T-TEST OF ADAS11
```{r}
# Missing values, impute from ADAS11.bl
idxs <- is.na(filt_AD$ADAS11)
filt_AD$ADAS11[idxs] <- filt_AD$ADAS11.bl[idxs]
if (sum(is.na(filt_AD$ADAS11)) != 0) # If NA remaining -> Impute with mean
{
  filt_AD$ADAS11[is.na(filt_AD$ADAS11)] = mean(filt_AD$ADAS11, na.rm=TRUE)
}


idxs <- is.na(filt_CN$ADAS11)
filt_CN$ADAS11[idxs] <- filt_CN$ADAS11.bl[idxs]
if (sum(is.na(filt_CN$ADAS11)) != 0)
{
  filt_CN$ADAS11[is.na(filt_CN$ADAS11)] = mean(filt_CN$ADAS11, na.rm=TRUE)
}

vt <- var.test(filt_AD$ADAS11, filt_CN$ADAS11, alternative="two.sided")

varbool <- FALSE
if(vt$p.value > 0.05){
  varbool <- TRUE
}

ADAS11test <- t.test(filt_AD$ADAS11, filt_CN$ADAS11, alternative="two.sided", var.equal=varbool)
ADAS11test
```

T-TEST OF ADAS13
```{r}
# Missing values, impute from ADAS13.bl
idxs <- is.na(filt_AD$ADAS13)
filt_AD$ADAS13[idxs] <- filt_AD$ADAS13.bl[idxs]
if (sum(is.na(filt_AD$ADAS13)) != 0) # If NA remaining -> Impute with mean
{
  filt_AD$ADAS13[is.na(filt_AD$ADAS13)] = mean(filt_AD$ADAS13, na.rm=TRUE)
}


idxs <- is.na(filt_CN$ADAS13)
filt_CN$ADAS13[idxs] <- filt_CN$ADAS13.bl[idxs]
if (sum(is.na(filt_CN$ADAS13)) != 0)
{
  filt_CN$ADAS13[is.na(filt_CN$ADAS13)] = mean(filt_CN$ADAS13, na.rm=TRUE)
}

vt <- var.test(filt_AD$ADAS13, filt_CN$ADAS13, alternative="two.sided")

varbool <- FALSE
if(vt$p.value > 0.05){
  varbool <- TRUE
}

ADAS13test <- t.test(filt_AD$ADAS13, filt_CN$ADAS13, alternative="two.sided", var.equal=varbool)
ADAS13test
```

SUMMARY TABLE
```{r}
st <- matrix(nrow=5, ncol=3)

sexcnmale <- sum(filt_CN$PTGENDER == "Male")
sexcnfemale <- sum(filt_CN$PTGENDER == "Female")

sexadmale <- sum(filt_AD$PTGENDER == "Male")
sexadfemale <- sum(filt_AD$PTGENDER == "Female")

st <- data.frame(st, row.names=c("Sex", "Age", "MMSE", "ADAS11", "ADAS13"))
colnames(st) <- c("CN", "AD", "p-value")

# Sex Row
st[1,1] <- paste(sexcnfemale,"F/",sexcnmale,"M", sep="")
st[1,2] <- paste(sexadfemale,"F/",sexadmale,"M", sep="")
st[1,3] <- paste(format(gender_chisq$p.value, digits=3), " (Chi sq.)", sep="")

# Age Row
agecn <- filt_CN$AGE
agead <- filt_AD$AGE
st[2,1] <- paste(format(mean(agecn), digits=3),"±", format(sd(agecn), digits=3), sep="")
st[2,2] <- paste(format(mean(agead), digits=3),"±", format(sd(agead), digits=3), sep="")
st[2,3] <- format(AGEtest$p.value, digits=3)

# MMSE Row
mmsecn <- filt_CN$MMSE
mmsead <- filt_AD$MMSE
st[3,1] <- paste(format(mean(mmsecn), digits=3),"±", format(sd(mmsecn), digits=3), sep="")
st[3,2] <- paste(format(mean(mmsead), digits=3),"±", format(sd(mmsead), digits=3), sep="")
st[3,3] <- format(MMSEtest$p.value, digits=3)

# ADAS11 Row
adas11cn <- filt_CN$ADAS11
adas11ad <- filt_AD$ADAS11
st[4,1] <- paste(format(mean(adas11cn), digits=3),"±", format(sd(adas11cn), digits=3), sep="")
st[4,2] <- paste(format(mean(adas11ad), digits=3),"±", format(sd(adas11ad), digits=3), sep="")
st[4,3] <- format(ADAS11test$p.value, digits=3)

# ADAS13 Row
adas13cn <- filt_CN$ADAS13
adas13ad <- filt_AD$ADAS13
st[5,1] <- paste(format(mean(adas13cn), digits=3),"±", format(sd(adas13cn), digits=3), sep="")
st[5,2] <- paste(format(mean(adas13ad), digits=3),"±", format(sd(adas13ad), digits=3), sep="")
st[5,3] <- format(ADAS13test$p.value, digits=3)
```


